use anyhow::Context as _;
use std::path::{Path, PathBuf};
use tokio::io::{AsyncBufReadExt, BufReader};
use tokio::process::Command;

const WAITING_PREFIX: &str = "[WAITING]";
const MAX_INSTALL_RETRIES: usize = 3;

pub struct IntegrationOutput {
    pub lines: Vec<String>,
    pub exit_code: i32,
}

/// Returns true if `tests/integration.py` exists for the skill.
pub fn has_integration_test(skill_dir: &Path) -> bool {
    skill_dir.join("tests").join("integration.py").is_file()
}

/// Signal file path for a skill: `.team/skill_signals/<skill_name>`.
pub fn signal_file_path(repo_root: &Path, skill_name: &str) -> PathBuf {
    repo_root
        .join(".team")
        .join("skill_signals")
        .join(skill_name)
}

/// Run `tests/integration.py` for a skill.
///
/// - Passes `RUSTPILOT_SIGNAL_FILE` env var so the script knows where to poll.
/// - Calls `on_waiting(message)` when the script prints `[WAITING] <message>`.
/// - Auto-installs missing pip packages (up to MAX_INSTALL_RETRIES attempts).
/// - Returns all output lines and exit code.
pub async fn run_integration_script(
    skill_dir: &Path,
    signal_file: &Path,
    on_waiting: impl Fn(String) + Send + Sync + 'static,
) -> anyhow::Result<IntegrationOutput> {
    let script = skill_dir.join("tests").join("integration.py");
    if !script.is_file() {
        return Ok(IntegrationOutput {
            lines: vec![],
            exit_code: 0,
        });
    }

    // Ensure signal dir exists and clear any stale signal.
    if let Some(parent) = signal_file.parent() {
        std::fs::create_dir_all(parent).ok();
    }
    let _ = std::fs::remove_file(signal_file);

    let on_waiting = std::sync::Arc::new(on_waiting);
    let mut retries = 0;

    loop {
        let output = run_once(&script, signal_file, on_waiting.clone()).await?;

        if output.exit_code != 0 {
            if let Some(module) = output.lines.iter().find_map(|l| extract_missing_module(l)) {
                if retries < MAX_INSTALL_RETRIES {
                    retries += 1;
                    eprintln!("[integration] auto-installing: {}", module);
                    auto_install(&module).await?;
                    continue;
                }
            }
        }

        return Ok(output);
    }
}

async fn run_once(
    script: &Path,
    signal_file: &Path,
    on_waiting: std::sync::Arc<impl Fn(String) + Send + Sync + 'static>,
) -> anyhow::Result<IntegrationOutput> {
    let mut child = Command::new("python")
        .arg(script)
        .env("RUSTPILOT_SIGNAL_FILE", signal_file)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .context("failed to spawn python — is Python installed?")?;

    let stdout = child.stdout.take().unwrap();
    let stderr = child.stderr.take().unwrap();

    // Collect stderr in a background task.
    let stderr_task = tokio::spawn(async move {
        let mut reader = BufReader::new(stderr).lines();
        let mut lines: Vec<String> = Vec::new();
        while let Ok(Some(line)) = reader.next_line().await {
            lines.push(format!("[stderr] {}", line));
        }
        lines
    });

    // Read stdout line-by-line on the current task; fire on_waiting immediately.
    let mut stdout_lines: Vec<String> = Vec::new();
    let mut stdout_reader = BufReader::new(stdout).lines();
    while let Ok(Some(line)) = stdout_reader.next_line().await {
        if line.starts_with(WAITING_PREFIX) {
            let msg = line[WAITING_PREFIX.len()..].trim().to_string();
            on_waiting(msg);
        }
        stdout_lines.push(line);
    }

    let status = child.wait().await?;
    let stderr_lines: Vec<String> = stderr_task.await.unwrap_or_default();

    stdout_lines.extend(stderr_lines);

    Ok(IntegrationOutput {
        lines: stdout_lines,
        exit_code: status.code().unwrap_or(-1),
    })
}

fn extract_missing_module(line: &str) -> Option<String> {
    let marker = "No module named '";
    let start = line.find(marker)? + marker.len();
    let end = line[start..].find('\'')?;
    let module = &line[start..start + end];
    Some(module.split('.').next().unwrap_or(module).to_string())
}

async fn auto_install(package: &str) -> anyhow::Result<()> {
    let status = Command::new("pip")
        .args(["install", "--quiet", package])
        .status()
        .await
        .with_context(|| format!("pip install {} failed", package))?;
    if !status.success() {
        anyhow::bail!("pip install {} failed", package);
    }
    // playwright also needs its browser binaries.
    if package == "playwright" {
        let _ = Command::new("playwright")
            .args(["install", "chromium"])
            .status()
            .await;
    }
    Ok(())
}

/// Template for `tests/integration.py` generated by `skill_create`.
pub fn integration_test_template() -> &'static str {
    r#"#!/usr/bin/env python3
"""
Integration test for this skill.

The test runner (skill_validate) will:
  - Run this script automatically.
  - Auto-install missing pip packages on ModuleNotFoundError.
  - Pause at wait_for_human() calls and send you a mail notification.
  - Resume when you call: skill_test_signal {"name": "<skill-name>"}

Exit 0 = PASSED, non-zero = FAILED.
"""
import os
import sys
import time


def wait_for_human(message: str) -> None:
    """Print a [WAITING] marker and block until the runner signals to continue."""
    signal_file = os.environ.get("RUSTPILOT_SIGNAL_FILE", "")
    print(f"[WAITING] {message}", flush=True)
    if signal_file:
        deadline = time.time() + 300  # 5-minute timeout
        while time.time() < deadline:
            if os.path.exists(signal_file):
                os.remove(signal_file)
                print("[RESUMED]", flush=True)
                return
            time.sleep(0.5)
        raise TimeoutError("Timed out waiting for human action (5 min)")
    else:
        input("Press Enter when done... ")
        print("[RESUMED]", flush=True)


# ── Write your test steps below ─────────────────────────────────────────────

def test_main():
    # Example for a Playwright-based skill:
    #
    # from playwright.sync_api import sync_playwright
    # with sync_playwright() as p:
    #     browser = p.chromium.launch(headless=False)
    #     page = browser.new_page()
    #     page.goto("https://example.com/login")
    #     page.screenshot(path="/tmp/test_qr.png")
    #
    #     wait_for_human("请扫描二维码: /tmp/test_qr.png")
    #
    #     assert "dashboard" in page.url, f"unexpected URL: {page.url}"
    #     print("✓ login ok")
    #     browser.close()
    raise NotImplementedError("Replace this with actual test steps")


if __name__ == "__main__":
    test_main()
    print("✓ All integration tests passed")
"#
}
